### ISSUE TITLE
cookies verify not consistent

### ISSUE THREAD

**Issue by marcoiora** [ccarruitero/makemehapi#147]
Cookies verifier second assertion is on authentication error being thrown by check-cookie.
Check-cookie is invoked passing the cookie in the right manner, and there is no blocking wait between set-cookie and check-cookie, so I think that the right response to check-cookie in this situation is the successfull {user: 'hapi'} one.

**Comment by kushalj** [comment]
Having a similar issue. The code verifies correctly when I change:

```
if (session) {
          result = { user: 'hapi' };
      } else {
          result = Boom.unauthorized('Missing Authentication!');
      }

```
to this:

```
     if (!session) {
          result = { user: 'hapi' };
      } else {
          result = Boom.badRequest('Invalid cookie value');
      }

```
which is just forcing the response it's checking for. So it looks like there could be something wrong.

**Comment by nmindz** [comment]
It seems like the test case for the Cookies test is expecting to fail the request and receive a HTTP 400 (Bad Request) with `Invalid cookie value` as a response string.

However the **solution** file will never match the expected result from the test. Although you can follow the logic and edit yourself to suit the test case, IMHO it is expected that the official solution solves the proposed test case.

My suggestion would be to either change the test case according to the solution file or correct the solution to comply with the test, whichever fits the objective within the Cookies exercise. As a demo:

```
Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    "[\"session=eyJrZXkiOiJtYWtlbWVoYXBpIn0=; Max-Age=0; Expires=Mon, 29 Aug 2016 16:07:17 GMT; Domain=localhost; Path=/\"]"
1.  EXPECTED:  "[\"session=eyJrZXkiOiJtYWtlbWVoYXBpIn0=; Max-Age=0; Expires=Mon, 29 Aug 2016 16:07:17 GMT; Domain=localhost; Path=/\"]"

Debug: state, error 
    {"header":"session=eyJrZXkiOiJtYWtlbWVoYXBpIn0=; Max-Age=0; Expires=Mon, 29 Aug 2016 16:07:17 GMT; Domain=localhost; Path=/","errors":[{"name":"Expires","value":"Mon, 29 Aug 2016 16:07:17 GMT","settings":{"strictHeader":true,"ignoreErrors":false,"isSecure":false,"isHttpOnly":false,"path":null,"domain":null,"ttl":null,"encoding":"none"},"reason":"Invalid cookie value"}]}
2.  ACTUAL:    "{\"user\":\"hapi\"}"
2.  EXPECTED:  "{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"Invalid cookie value\"}"


────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to COOKIES didn't pass. Try again!
```

I copied the handler codes from the solution just to be extra sure and as expected, the test is just expecting a different response altogether. Needs to be reviewed. This is _dangerously misleading_ for those with little to no experience in programming that might happen to be trying Node/Javascript and HAPI as their first.

**Comment by ccarruitero** [comment]
Hi @marcoiora , @kushalj , @nmindz 

The solution for the cookies exercises was wrong. This was fixed in https://github.com/ccarruitero/makemehapi/commit/1b2ec73104a9f354dbba59b92acb71350b5d478c and is available in the new version that published in npm https://www.npmjs.com/package/makemehapi
