### ISSUE TITLE
`makemehapi run server.js` keeps the port in use

### ISSUE THREAD

**Issue by vfonic** [ccarruitero/makemehapi#186]
Hi,

While working on solution for `hello_hapi`, I've let the server take predefined port number:
```js
server.connection({
  port: 8080
});
```

After running `makemehapi run server.js`, I got the following error (which makes sense):
```sh
Server running at: http://localhost:8080
✗ Error connecting to http://localhost:34817: ECONNREFUSED
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:34817
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

However, on the second run, I get the following error (**Error: listen EADDRINUSE 127.0.0.1:8080**):
```sh
/Users/viktorfonic/MEGAsync/Developer/JavaScript/makemehapi/lib/server/index.js:26
    throw err;
    ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
✗ Error connecting to http://localhost:39433: ECONNREFUSED
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:39433
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

I also checked with `node server.js` and I get the same error. Is there any way to release the port before the "test" throws an error?

**Comment by fiveisprime** [comment]
Are you sure that you didn't just have `$ node server.js` running in a different window/tab? There's no way for the "randomly" generated port to be `8080` so you probably had the code running somewhere else and using up the port.

Can you verify and let me know? If you have the same issue, provide the steps to repro and I'll dig in!

**Comment by vfonic** [comment]
Steps to repro:

Use this configuration (wrong for solution, but doesn't matter now) for `server.connection({})`:
```js
server.connection({
  host: 'localhost',
  port: 9000 // note the fixed port number, could be any number
});
```

Run `$ makemehapi verify server.js`.

Expected:
Verification throws an error / fails
Port 9000 is free for future use

Actual:
Verification throws an error / fails (same as above)
Port 9000 is in use

You can verify this by:
1. Going to http://localhost:900 and see the hapi serving content or
2. See that you have an extra node process in Activity Monior (macOS)
3. Run `node server.js` and see that it fails
4. Run `makemehapi verify server.js` again and see that it fails (with the same error like `node server.js`, but different error from the first run)

The issue happens after the user error: when user doesn't allow for having the port number specified as command line argument, but hard-codes a number (totally possible scenario - actually that's exactly what happened to me). The final outcome should be that the port is released before the makemehapi verification throws an error.

**Comment by vfonic** [comment]
I just noticed that every time `makemehapi verify` command fails, it leaves several node processes running.

I've just ran `makemehapi verify` and it created 2 new processes that didn't terminate when the script stopped executing.

**Comment by johnking** [comment]
Is this issue fixed? I found the same issue.  @fiveisprime
